#import "@preview/marginalia:0.3.1" as marginalia: note, notefigure, wideblock
#import "config.typ": config

#set document(title: "Sítě v Linuxu")

#show: marginalia.setup.with(
  inner: (far: 1cm, width: 0cm, sep: 1cm),
  outer: (far: 1cm, width: 5cm, sep: 1cm),
  top: 2cm,
  bottom: 2cm,
)
#show: config

#title()


= Síťová rozhraní

Síťové rozhraní (*network interface*) je softwarový bod, přes který systém komunikuje se sítí. V~Linuxu se rozlišují dva hlavní typy pojmenování:

- *Starší pojmenování:* `eth0`, `wlan0`.
- *Prediktabilní pojmenování:* `enp0s3`, `ens33`, `wlp2s0`.

Dnes je standardem používat nová jména, protože jsou *předvídatelná a~stabilní* #note[U starých názvů hrozilo, že se po restartu systému, aktualizaci jádra nebo změně v~BIOSu změní v~návaznosti na danou síťovou kartu.].

Speciálním rozhraním je `lo` (loopback) s~adresou `127.0.0.1`, které slouží k~vnitřní komunikaci systému se sebou samým.

== Správa rozhraní v~příkazové řádce

Pro zobrazení informací o~rozhraních se dnes používá nástroj `ip` z~balíku `iproute2`. Příkaz `ip a` ukáže všechna rozhraní, jejich aktuální stav a~přidělené IP adresy.

```bash
$ ip -br a
lo               UNKNOWN        127.0.0.1/8 ::1/128
enp3s0           UP             192.168.1.100/24
```

Starší nástroj `ifconfig` je již považován za zastaralý, ačkoliv se s~ním lze stále setkat na systémech BSD nebo velmi starých distribucích.#note[Nástroj `ifconfig`, společně se dalšími podobnými nástroji, je možné nainstalovat. Často jsou dostupné jako balík pod názvem `net-tools`.]

= IP adresy

Linux umožňuje nastavovat adresy buď dynamicky (např. přes DHCP), nebo staticky.

== Statické nastavení

Statickou adresu lze přidat přímo za běhu systému, ale toto nastavení zmizí po restartu.

```bash
sudo ip addr add 192.168.1.200/24 dev enp3s0
sudo ip link set enp0s3 up
```

== Trvalá konfigurace

Pro trvalé uložení adres je nutné využít správce sítě#note[Například _NetworkManager_, avšak správce sítě se může na různých systémech lišit.] nebo upravit konfigurační soubor `/etc/network/interfaces`. Zde je příklad takové konfigurace:

#box(
```text
auto enp3s0
iface enp3s0 inet static
    address 192.168.1.100
    netmask 255.255.255.0
    gateway 192.168.1.1
```
)

= Směrování & ARP

Routa (směrování) říká systému, kam má posílat pakety, pokud se cílová adresa nachází mimo lokální síť.

Existující routy lze opět zobrazit nástrojem `ip`.#note[Klíčové slovo *default* nastavuje tzv. výchozí bránu, což je typicky síťový router. Bez této cesty není možný přístup k~Internetu.]

```bash
$ ip r
default via 192.168.1.1 dev enp0s3
192.168.1.0/24 dev enp0s3 proto kernel scope link
```

Pro doručení v~rámci lokální sítě využívá systém protokol *ARP* (*Address Resolution Protocol*)#note[V sítích IPv6 je protokol ARP nahrazen podobně fungujícím protokolem *NDP* (*Neighbor Discovery Protocol*).], který mapuje IP adresy na fyzické MAC adresy.

```bash
$ ip neigh
192.168.1.20 dev enp3s0 lladdr 00:a0:98:0e:00:00 STALE
192.168.1.10 dev enp3s0 lladdr a8:b8:e0:0a:00:00 REACHABLE
```

Tento proces probíhá průběžně automaticky behem komunikace do sítě. ARP záznamy jsou pouze dočasné a~obsah směrovací tabulky se neustále aktualizuje.#note[Je moné nastavit statické záznamy a~tím předejít zbytečné ARP komunikaci v~síti.]

= DNS

DNS je systém, který umožňuje přeložit čitelný název domény, například _it.pedf.cuni.cz_, na příslušnou IP adresu serveru.

Operační systém získává tyto informace z~takzvaných _nameserverů_. ty jsou nastavené v~souboru `/etc/resolv.conf`, nebo 

```bash
$ cat /etc/resolv.conf
# Generated by resolvconf
nameserver 192.168.1.1
nameserver 192.168.1.2
```

Asociace IP adresy k~domméně může být zároveň na systému nakonfigurována v~soboru `/etc/hosts`, který může obsahovat volitelné domény, například:

```
192.168.1.10 mujserver.lan mujserver
```

Po navštívení domény _mujserver.lan_ nastane přesměrování na adresu _192.168.1.10_ bez nutnosti odesílání dostazu na DNS server.

Pro ověření fungování DNS můžeme požít nástroj `dig`, který vyhledává informace o~konkrétním vzdáleném serveru.

```bash
$ dig +short it.pedf.cuni.cz
it-new.pedf.cuni.cz.
195.113.39.3
```

= Diagnostika & analýza sítě

Pro řešení problémů a~analýzu provozu existuje v~Linuxu řada programů. Zde jsou příklady některých užitečních nástrojů:

1. *ss:* Analýza soketů a~procesů na lokálním zařízení.#note[Program `ss` nahrazuje starší nástroj s~názvem `netstat`. Pro zobrazení názvů procesů je nutné program `ss` pouštět pod uživatelem `root`.]
2. *Ping:* Základní ověření dostupnosti hostitele. Zároveň může ověřit, zda funguje DNS resolving.
3. *Nmap:* Skenování sítě, zjišťování otevřených portů a~běžících služeb.
4. *Tcpdump:* Analýza paketů, studium a~ladění síťové komunikace.

```bash
# Výpis procesů a~na jakých adresách/portech poslouchají
ss -tulpn
```
```bash
# Ověření dostupnosti vzdáleného zařízení
ping 1.1.1.1
```
```bash
# Ověření zda zařízení na cílové adrese poslouchá na portu 80
nmap -p 80 192.168.200.200
```
```bash
# Sledování HTTP provozu na rozhraní enp0s3
tcpdump -i enp0s3 port 80
```

= Firewall

Firewall v~Linuxu filtruje příchozí a~odchozí provoz na základě definovaných pravidel.

- *iptables:* Starší systém, dnes v~"deprecated" režimu.
- *nftables:* Moderní náhrada, která je výkonnější, přehlednější a~doporučená pro budoucí použití.#note[Základní koncept nftables tvoří tabulky (*tables*), řetězce (*chains*) a~jednotlivá pravidla (*rules*).]

V~případě provozování služeb pomocí kontejnerů je firewall využíván k~mapování (směrování) portů do jednotlivých kontejnerů.
